services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  # Port for Neo4j web interface
      - "7687:7687"  # Port for Neo4j Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/your_password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,db.index.vector
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,db.index.vectorapoc.*

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - mynetwork
    restart: unless-stopped 

  # fastapi:
  #   image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
  #   container_name: fastapi
  #   volumes:
  #     - ./app:/app
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - mynetwork
  #   depends_on:
  #     - neo4j
  #   environment:
  #     - NEO4J_URI=bolt://neo4j:7687
  #     - NEO4J_USER=neo4j
  #     - NEO4J_PASSWORD=your_password




volumes:
  neo4j_data:
  neo4j_logs:

networks:
  mynetwork:
