version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: pgner
    env_file:
      - ../.env
    volumes:
      - pgner_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - pgner-network

  adminer:
    image: adminer:latest
    container_name: neradminer
    env_file:
      - ../.env
    depends_on:
      - postgres
    ports:
      - "8086:8080"
    networks:
      - pgner-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: nermlflow
    env_file:
      - ../.env
    ports:
      - "${MLFLOW_PORT:-5000}:5000"
    volumes:
      - mlflow_data:/mlflow
    networks:
      - pgner-network
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0 --port 5000

  prometheus:
    image: prom/prometheus:latest
    container_name: nerprometheus
    env_file:
      - ../.env
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT:-9000}:9090"
    networks:
      - pgner-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgner_data:
  mlflow_data:

networks:
  pgner-network:
    driver: bridge
